num_um = float(input().strip())
num_dois = float(input().strip())

a_str = str(num_um)
b_inteiro = int(num_dois)
b_int_str = str(b_inteiro)
print(num_um + num_dois)                  
print(a_str + b_int_str)     
print(num_um * num_dois)                  
print(a_str * int(num_dois))         
print(num_um / num_dois)                  
print(num_um // num_dois)                
print(num_um ** num_dois)                 
print(num_um % num_dois)      